# Generated by Django 5.2.8 on 2025-12-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options_listing_city_listing_pincode_and_more'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='listings.listing'),
        ),
    ]
