# Generated by Django 5.2.8 on 2025-12-02 10:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='nagpur', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('BOOK', 'Book'), ('NOTE', 'Notes'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category'], name='listings_li_categor_4dd4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['pincode'], name='listings_li_pincode_68d0d9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='listings_li_created_92fa22_idx'),
        ),
    ]
